# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 417)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.in_btn = QtWidgets.QPushButton(Form)
        self.in_btn.setObjectName("in_btn")
        self.gridLayout.addWidget(self.in_btn, 0, 0, 1, 1)
        self.out_btn = QtWidgets.QPushButton(Form)
        self.out_btn.setObjectName("out_btn")
        self.gridLayout.addWidget(self.out_btn, 1, 0, 1, 1)
        self.in_lbl = QtWidgets.QLabel(Form)
        self.in_lbl.setText("")
        self.in_lbl.setObjectName("in_lbl")
        self.gridLayout.addWidget(self.in_lbl, 0, 1, 1, 1)
        self.run_btn = QtWidgets.QPushButton(Form)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 3, 0, 1, 2)
        self.log_txt = QtWidgets.QPlainTextEdit(Form)
        self.log_txt.setReadOnly(True)
        self.log_txt.setObjectName("log_txt")
        self.gridLayout.addWidget(self.log_txt, 4, 0, 1, 2)
        self.out_lbl = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_lbl.sizePolicy().hasHeightForWidth())
        self.out_lbl.setSizePolicy(sizePolicy)
        self.out_lbl.setText("")
        self.out_lbl.setObjectName("out_lbl")
        self.gridLayout.addWidget(self.out_lbl, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ImageExpress Converter"))
        self.in_btn.setText(_translate("Form", "Input Directory"))
        self.out_btn.setText(_translate("Form", "Output Directory"))
        self.run_btn.setText(_translate("Form", "Run"))
